export function createGoogleCalendarUrl(title: string, durationMinutes: number, description: string): string {
  const base = "https://calendar.google.com/calendar/render?action=TEMPLATE";
  
  // Create logical start and end dates
  const now = new Date();
  const start = new Date(now.getTime() + 10 * 60 * 1000); // Start 10 mins from now
  const end = new Date(start.getTime() + durationMinutes * 60 * 1000);
  
  const formatTime = (d: Date) => d.toISOString().replace(/-|:|\.\d\d\d/g, "");
  
  return `${base}&text=${encodeURIComponent("DeadlineOS: " + title)}&dates=${formatTime(start)}/${formatTime(end)}&details=${encodeURIComponent(description + "\n\nGenerated by DeadlineOS - Your AI Deadline Rescue Agent")}&sf=true&output=xml`;
}

export function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard) {
    return navigator.clipboard.writeText(text).then(() => true).catch(() => false);
  }
  // Fallback for security contexts without full clipboard API in sandbox
  try {
    const textArea = document.createElement("textarea");
    textArea.value = text;
    textArea.style.position = "fixed";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return Promise.resolve(successful);
  } catch (err) {
    return Promise.resolve(false);
  }
}
